FROM ubuntu:latest

ARG JWT_KEY
ARG TWILIO
ARG DB_CONNECTION
ARG SPACES_KEY
ARG SPACES_SECRET

WORKDIR /bout

ENV JWT_KEY=$JWT_KEY
ENV TWILIO=$TWILIO
ENV DB_CONNECTION=$DB_CONNECTION
ENV SPACES_KEY=$SPACES_KEY
ENV SPACES_SECRET=$SPACES_SECRET


# Copy our build
COPY ./target/release/bout-backend ./

CMD ["/bout/bout-backend"]

EXPOSE 80