[debug]
address = "0.0.0.0"
port = 443
workers = 2
keep_alive = 5
read_timeout = 5
write_timeout = 5
log = "critical"
limits = { forms = 32768 }
tls = { certs = "/Users/colton/Development/mob-backend/mob.spacedoglabs.com.cer", key = "/Users/colton/Development/mob-backend/mob.spacedoglabs.com.pem" }

[release]
address = "0.0.0.0"
port = 443
workers = 2
keep_alive = 5
read_timeout = 5
write_timeout = 5
log = "critical"
limits = { forms = 32768 }
