[debug]
address = "0.0.0.0"
port = 80
workers = 2
keep_alive = 5
read_timeout = 5
write_timeout = 5
log = "critical"
limits = { forms = 32768 }
twilio = ""
jwt_secret = "thisisatestkey"

[debug.databases.mob]
url = "mysql://root:test123@localhost:49492/mob"

[release]
address = "0.0.0.0"
port = 80
workers = 2
keep_alive = 5
read_timeout = 5
write_timeout = 5
log = "critical"
limits = { forms = 32768 }
twilio = ""
jwt_secret = ""

[release.databases.mob]
url = ""
