name: Release

on:
  push:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: toml editor
        uses: ciiiii/toml-editor@1.0.0
        with:
          # The relative path of toml file
          file: Rocket.toml
          key: release.databases.mob.url
          value: ${{ secrets.MONGO_DB }}
      - name: Build
        run: cargo build
      - name: Build image
        run: docker build -t registry.digitalocean.com/mob/backend:latest .
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DOCKER_LOGIN }}
      - name: Log in to DO Container Registry
        run: doctl registry login --expiry-seconds 600
      - name: Push image to DO Container Registry
        run: docker push registry.digitalocean.com/mob/backend:latest
