name: Release

on:
  push:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Get Crate Version
        id: crate-version
        uses: colathro/crate-version@1.0.0
        with:
          file: "./Cargo.toml"

      - name: Build
        run: cargo build --release

      - name: Test Validation
        run: cargo test -p validation --release

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DOCKER_LOGIN }}

      - name: Log in to DO Container Registry
        run: doctl registry login --expiry-seconds 6000

      - name: Check if Version Already Exists in Container Registry
        id: version-exists
        continue-on-error: true
        run: docker manifest inspect registry.digitalocean.com/spacedoglabs/backends:bout-${{steps.crate-version.outputs.version}} > /dev/null | echo "container_exists=$?" >> $GITHUB_ENV

      - name: Build image
        run: |
          if echo ${{ env.container_exists  == '0' }} | grep -c "true"
          then
            echo "Skipped Building an Image. Image was found."
          else
            docker build -t registry.digitalocean.com/spacedoglabs/backends:bout-${{steps.crate-version.outputs.version}} . --build-arg JWT_KEY="${{ secrets.JWT_SECRET }}" --build-arg TWILIO="${{ secrets.TWILIO_KEY }}" --build-arg "DB_CONNECTION=${{ secrets.MONGO_DB }}" --build-arg "SPACES_KEY=${{ secrets.SPACES_KEY }}" --build-arg "SPACES_SECRET=${{ secrets.SPACES_SECRET }}"
          fi

      - name: Push image to DO Container Registry
        run: |
          if echo ${{ env.container_exists  == '0' }} | grep -c "true"
          then
            echo "Skipped Building an Image. Image was found."  
          else
            docker push registry.digitalocean.com/spacedoglabs/backends:bout-${{steps.crate-version.outputs.version}}
          fi

      - name: Set up kubectl
        uses: matootie/dokube@v1.4.0
        with:
          personalAccessToken: ${{ secrets.DOCKER_LOGIN }}
          clusterName: spacedoglabs

      - name: Get nodes
        run: |
          if echo ${{ env.container_exists  == '0' }} | grep -c "true"
          then
            echo "Skipped updating deployed image."
          else
            kubectl set image deployment/bout-deployment backend=registry.digitalocean.com/spacedoglabs/backends:bout-${{steps.crate-version.outputs.version}}
          fi
