name: Release

on:
  push:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: ${{ secrets.MONGO_DB }}

    steps:
      - uses: actions/checkout@v3

      - name: Install Protoc
        uses: arduino/setup-protoc@v1

      - name: Install sqlx-cli
        run: cargo install sqlx-cli

      - name: Add IP to Database Trusted Sources
        uses: review-with-friends/manage-db-action@giga-1
        with:
          action: "add"
          database_id: "402172b2-958a-4edf-818d-6d43ed277996"
          digitalocean_token: ${{ secrets.DOCKER_LOGIN }}

      - name: Run sqlx migrations
        run: sqlx migrate run --ignore-missing

      - name: Build
        run: cargo build --release

      - name: Test Validation
        run: cargo test -p validation --release

      - name: Remove IP from Database Trusted Sources
        uses: review-with-friends/manage-db-action@giga-1
        if: always()
        with:
          action: "remove"
          database_id: "402172b2-958a-4edf-818d-6d43ed277996"
          digitalocean_token: ${{ secrets.DOCKER_LOGIN }}

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DOCKER_LOGIN }}

      - name: Log in to DO Container Registry
        run: doctl registry login --expiry-seconds 6000

      - name: Build image
        run: docker build -t registry.digitalocean.com/spacedoglabs/backends:reviewwithfriends . --build-arg JWT_KEY="${{ secrets.JWT_SECRET }}" --build-arg TWILIO="${{ secrets.TWILIO_KEY }}" --build-arg "DB_CONNECTION=${{ secrets.MONGO_DB }}" --build-arg "SPACES_KEY=${{ secrets.SPACES_KEY }}" --build-arg "SPACES_SECRET=${{ secrets.SPACES_SECRET }}" --build-arg "NR_KEY=${{ secrets.NR_KEY }}" --build-arg "APN_KEY=${{ secrets.APN_KEY }}" --build-arg "SENDGRID_KEY=${{ secrets.SENDGRID_KEY }}" --build-arg "GITHUB_KEY=${{ secrets.GH_KEY }}"

      - name: Push image to DO Container Registry
        run: docker push registry.digitalocean.com/spacedoglabs/backends:reviewwithfriends
